NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 50
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 60
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 20
NDefines.NCountry.ABDICATE_LEGITIMACY_HIT = -50
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -20