NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_GAIN = 5
NDefines.NDiplomacy.PO_ANNEX_PRESTIGE = 0.1						-- _DDEF_PO_ANNEX_PRESTIGE = 10, (No effect on loser :)
NDefines.NDiplomacy.PO_DEMAND_PROVINCES_PRESTIGE = 0.1				-- _DDEF_PO_DEMAND_PROVINCES_PRESTIGE = 10, (Per development)
NDefines.NDiplomacy.PO_REVOKE_CORES_PRESTIGE = 0.05 					-- _DDEF_PO_REVOKE_CORES_PRESTIGE = 10, (Per development)
NDefines.NDiplomacy.PO_RETURN_CORES_PRESTIGE = 0.1 					-- (Per development)
NDefines.NDiplomacy.PO_RELEASE_VASSAL_PRESTIGE = 0.1 				-- _DDEF_PO_RELEASE_VASSAL_PRESTIGE = 10,
NDefines.NDiplomacy.PO_TRANSFER_VASSAL_PRESTIGE = 0.1
NDefines.NDiplomacy.PO_RELEASE_ANNEXED_PRESTIGE = 0.1
NDefines.NDiplomacy.PO_FORM_PU_PRESTIGE = 0.1 						-- _DDEF_PO_FORM_PU_PRESTIGE = 10,
NDefines.NDiplomacy.PO_BECOME_VASSAL_PRESTIGE = 0.1 					-- _DDEF_PO_BECOME_VASSAL_PRESTIGE = 10,
NDefines.NDiplomacy.PO_CONCEDE_DEFEAT_PRESTIGE = 5 				-- _DDEF_PO_CONCEDE_DEFEAT_PRESTIGE_
NDefines.NDiplomacy.PO_DISMANTLE_REVOLUTION_PRESTIGE = 10
NDefines.NDiplomacy.PO_CHANGE_HRE_RELIGION_PRESTIGE = 5
NDefines.NDiplomacy.PO_ANNUL_TREATY_PRESTIGE = 0.5 					-- _DDEF_PO_ANNUL_TREATY_PRESTIGE = 10,
NDefines.NDiplomacy.PO_REVOKE_ELECTOR_AE = 25
NDefines.NDiplomacy.PO_REVOKE_ELECTOR_PRESTIGE = 3
NDefines.NDiplomacy.PO_TRADE_POWER_PRESTIGE = 1
NDefines.NDiplomacy.PO_CONCEDE_COLONIAL_PRESTIGE = 0.5
NDefines.NDiplomacy.PO_GIVE_UP_CLAIM_PRESTIGE = 1
NDefines.NDiplomacy.PO_HUMILIATE_RIVAL_PRESTIGE = 3
NDefines.NDiplomacy.PO_FORCE_MIGRATION_PRESTIGE = 1
NDefines.NDiplomacy.PO_ENFORCE_REBEL_DEMANDS_PRESTIGE = 1
NDefines.NDiplomacy.PO_TAKE_MANDATE_PRESTIGE = 5
NDefines.NDiplomacy.PO_ENFORCE_FLEET_BASING_PRESTIGE = 1
NDefines.NDiplomacy.PO_ENFORCE_MIL_ACCESS_PRESTIGE = 1
NDefines.NDiplomacy.PO_WAR_REPARATIONS_PRESTIGE = 1
NDefines.NDiplomacy.PO_END_RIVALRY_PRESTIGE = 3
NDefines.NDiplomacy.ELECTIVE_VICTORY_PRESTIGE = 10
NDefines.NDiplomacy.PO_CHANGE_RELIGION_PRESTIGE = 0 				-- _DDEF_PO_CHANGE_RELIGION_PRESTIGE = 10
