NDefines.NCountry.PS_ADVANCE_TECH = 200                    -- New tech mechanics
NDefines.NCountry.PS_BUY_IDEA = 400
NDefines.NCountry.PS_MAKE_PROVINCE_CORE = 0                --New Core System
NDefines.NCountry.PS_REDUCE_INFLATION = 100000
NDefines.NCountry.PS_REPLACE_RIVAL = 50
NDefines.NCountry.PS_ATTACK_NATIVES = 2
NDefines.NCountry.PS_CHANGE_GOVERNMENT = 200
NDefines.NCountry.PS_STRENGTHEN_GOVERNMENT = 9999
NDefines.NCountry.PS_CHANGE_CULTURE = 9999
NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 100000
NDefines.NCountry.PS_FACTION_BOOST = 33
NDefines.NCountry.PS_LOWER_TARIFFS = 50
NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 0
NDefines.NCountry.PS_IMPROVE_PROVINCE_MUL = 0
NDefines.NCountry.PS_IMPROVE_PROVINCE_CAPITAL_DISCOUNT = 0.005
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 9999
NDefines.NCountry.PS_BUY_GENERAL = 50
NDefines.NCountry.PS_BUY_ADMIRAL = 30
NDefines.NCountry.PS_BUY_CONQUISTADOR = 40
NDefines.NCountry.PS_BUY_EXPLORER = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 20
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 40									   
NDefines.NCountry.PS_BOOST_MILITARIZATION = 9999
NDefines.NCountry.PS_SET_PRIMARY_CULTURE = 1000
NDefines.NCountry.PS_ADD_ACCEPTED_CULTURE = 100
NDefines.NCountry.PS_REMOVE_ACCEPTED_CULTURE = 50
NDefines.NCountry.PS_BOOST_STABILITY = 0
NDefines.NCountry.PS_HARSH_TREATMENT_COST = 150					-- Max cost for harsh treatment (scales to revolt size)
NDefines.NCountry.PS_HARSH_TREATMENT_REDUCE = 25
NDefines.NCountry.PS_ESTABLISH_SIBERIAN_FRONTIER = 5