NDefines.NReligion.MAX_CHURCH_POWER = 250
NDefines.NReligion.ASPECT_REMOVE_COST = 0
NDefines.NReligion.PIETY_CORRUPTION = -1
NDefines.NReligion.PIETY_MANPOWER = 1.0
NDefines.NReligion.KARMA_TOO_HIGH = 20
NDefines.NReligion.KARMA_TOO_LOW = -20
NDefines.NReligion.KARMA_JUST_RIGHT_HIGH = 20
NDefines.NReligion.KARMA_JUST_RIGHT_LOW = -20
NDefines.NReligion.KARMA_FOR_HONORING_CTA = 15
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = -10
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = 0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.00 			-- 0%
NDefines.NCountry.ANCESTOR_PERSONALITY_LEVEL_1 = 12				-- Roof of first level of ancestor personality
NDefines.NCountry.ANCESTOR_PERSONALITY_LEVEL_2 = 0				-- Roof of second level of ancestor personality
NDefines.NCountry.ANCESTOR_COST = 50
NDefines.NReligion.REFORM_DESIRE_PER_YEAR = 0.008 --from 0.002